version: "3.9"
services:

  web:
    container_name: hemmah_backend
    build: .
    ports:
      - "5151:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://hemmah_backend_mysql:3306/hemmah_prod
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: test55@Good
    # volumes:
     #   - /home/ubuntu/hemmah_backend/volume:.
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: hemmah_backend_mysql
    image: mysql:8
    ports:
      - "3003:3306"
    # volumes:
    #  - /home/ubuntu/hemmah_backend/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: hemmah_prod
      MYSQL_USER: hemmah_app
      MYSQL_PASSWORD: test55@Good
      MYSQL_ROOT_PASSWORD: test55@Good
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 30s
        timeout: 10s
        retries: 3

