spring:
  profiles:
    active: dev

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: 'true'
        ddl-auto: create-drop
    show-sql: true
    generate-ddl: true

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

firebase:
  service-account-file: ./src/main/resources/certs/hemmah_firebase_creds.json

server:
  error:
    include-message: always
    path: /error
#    whitelabel:
#      enabled: false