spring:
  profiles:
    active: dev

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: 'true'
        ddl-auto: create-drop
    generate-ddl: true


  jackson:
    serialization:
      order-map-entries-by-keys: true
    parser:
      allow-single-quotes: true

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 5MB


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

firebase:
  service-account-file: classpath:/static/hemmah_firebase_creds.json


server:
  error:
    include-message: always
    path: /error
#    whitelabel:
#      enabled: false

twilio:
  #  ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
  #  API_SID: ${TWILIO_API_SID}
  #  API_SECRET: ${TWILIO_API_SECRET}

  ACCOUNT_SID: "ACd48368859fda2cb695464a585bfba51f"
  API_SID: "SK80606a85a194aea9b9621b19fe62332c"
  API_SECRET: "IRmKatYAbdoRPGA4rdOlsCBWTYZxfwhp"

