spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hemah_dev?createDatabaseIfNotExist=true
    username: hemah_app
    password: test55@good

  jpa:
    show-sql: true


logging:
  level:
    org:
      help:
        hemah: debug